# 
# Basics of CloudFormation
# 
AWSTemplateFormatVersion: 2010-09-09

Description: DevDay - Chef Workstation

Parameters:
  # 
  # PathToStarterKit - the starter kit provided when you launched
  #                    the OpsWorks for Chef Automate service
  PathToStarterKit:
    Type: String
    Description: 'Enter the S3 path where the starter kit is located. ex: s3://opsworks-cm-demo-bucket/chef-demo_starter_kit.zip'
    MinLength: 10

  # SubnetID - Select the subnets the resources will use
  SubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: 'Subnet to deploy EC2 instance into'

  VpcID:
    Type: AWS::EC2::VPC::Id
    Description: 'Select the VPC to use'

  # KeyName - required to create instances
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: 'Name of an existing EC2 KeyPair to enable SSH access to the instance'

Resources:
  # IAM Role
  # --------
  # ChefWorkstationRole - This role provides more access 
  # than you would normally grant. However, for the sake 
  # of this tutorial, we will need access to a number of 
  # services. Make sure you tailor your role to the purpose.
  ChefWorkstationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: 'Allow'
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ChefWorkstationPolicy
          PolicyDocument: 
            Version: 2012-10-17
            Statement:
              - Action:
                  - 'ec2:*'
                  - 'cloudwatch:*'
                  - 's3:*'
                  - 'sns:*'
                  - 'cloudformation:*'
                  - 'iam:PassRole'
                  - 'opsworks-cm:AssociateNode'
                  - 'opsworks-cm:DescribeNodeAssociationStatus'
                  - 'opsworks-cm:DisassociateNode'
                Resource: '*'
                Effect: Allow

  # SecurityGroup
  # -------------
  # ChefWorkstationSG - We will need inbound access for SSH. 
  # If you need access for HTTP/S traffic, uncomment the 
  # lines below.
  ChefWorkstationSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Allow SSH, HTTP, and HTTPS access to the instance'
      VpcId: !Ref VpcID
      SecurityGroupIngress:
        - FromPort: 22
          ToPort: 22
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
        # - FromPort: 80
        #   ToPort: 80
        #   IpProtocol: tcp
        #   CidrIp: 0.0.0.0/0
        # - FromPort: 443
        #   ToPort: 443
        #   IpProtocol: tcp
        #  CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: ChefWorkstationSG

  # InstanceProfile
  # ---------------
  # ChefWorkstationProfile - This profile contains the role 
  # created above (ChefWorkstationChef).
  ChefWorkstationProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: '/'
      Roles:
        - !Ref ChefWorkstationRole

  # EC2Instance
  # ------------
  # ChefWorkstation - Our workstation will install all 
  # necessary software once it's been created. When you 
  # login, you will be able to start using chefdk.
  ChefWorkstation:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-a4dc46db
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroupIds: 
        - !Ref ChefWorkstationSG
      SubnetId: !Ref SubnetID
      IamInstanceProfile: !Ref ChefWorkstationProfile
      UserData:
        Fn::Base64: !Sub |
              #!/bin/bash -ex
              export DEBIAN_FRONTEND=noninteractive;
              pwd;
              apt-get update;
              apt-get -y upgrade;
              apt-get install -y apache2;
              apt-get install -y awscli;
              apt-get install -y unzip;
              echo "<html>My first CloudFormation template</html>" > /var/www/html/index.html;
              cd /var/www/html;
              chmod 755 index.html;
              service apache2 start;
              update-rc.d apache2 start defaults;
              wget https://packages.chef.io/files/stable/chefdk/3.0.36/ubuntu/16.04/chefdk_3.0.36-1_amd64.deb;
              dpkg -i ./chefdk_3.0.36-1_amd64.deb;
              cd /home/ubuntu
              aws s3 cp ${PathToStarterKit} .;
              unzip *starter_kit.zip -d starterkit;
              find starterkit -type d -name '.chef' -exec cp -r {} . \;
              chown -R ubuntu:ubuntu .
              # cp -r ./.chef /etc/chef/;
              # mv starterkit/*/* starterkit/;
      Tags:
        -
          Key: Name
          Value: CloudFormation Test
        -
          Key: Environment
          Value: CFNTest

#Outputs:
#  PublicIP:
#    Description: Public IP Address of the instance
#    Value: !GetAtt ChefWorkstation.PublicIp
