---
AWSTemplateFormatVersion: 2010-09-09
Description: DevDay - Basic CFN Template
Parameters:
  SubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet to deploy EC2 instance into
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - m4.large
    - m5.large
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-b70554c8
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetID
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -ex
          yum install -y httpd;
          echo "<html>My first CloudFormation template!</html>" > /var/www/html/index.html;
          cd /var/www/html;
          chmod 755 index.html;
          service httpd start;
          chkconfig httpd on;
      Tags:
      - Key: Name
        Value: CloudFormation Test
      - Key: Environment
        Value: CFNTest
...
